---
- src: git@git-service.ait.ac.at:sct-cyberrange/ansible-roles/apache2.git
  path: /etc/ansible/roles/cyber-range/apache2
  scm: git
  version: master
  name: apache2

- src: git@git-service.ait.ac.at:sct-cyberrange/ansible-roles/mariadb.git
  path: /etc/ansible/roles/cyber-range/mariadb
  scm: git
  version: master
  name: mariadb