---
# tasks file for wordpress

# mysql 
# php 

- name: Updating apt-Cache
  apt:
    update_cache: yes
  become: yes
  tags: [install]


- name: Install apache2
  include_role:
    name: apache2
    apply:
      tags: [install]
  vars: 
    apache2_packages: libapache2-mod-php7.2 # Ubuntu 18.04
  tags: [install]


- name: Install MySQL
  include_role:
    name: mysql
    apply:
      tags: [install]
  tags: [install]


- name: Install required packages
  package:
      name: [php7.2, php7.2-mysql, php7.2-gd, php7.2-ssh2]
      state: present
  tags: [install]


# -----------------------------------------------------------------------


- name: Download WordPress  
  get_url: 
    url: https://wordpress.org/latest.tar.gz 
    dest: /tmp/wordpress.tar.gz
    validate_certs: no


- name: Extract WordPress  
  unarchive: 
    src: /tmp/wordpress.tar.gz 
    dest: /var/www/ 
    copy: no 


- name: Update default Apache site
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-enabled/000-default.conf
    # owner: "{{ wp_user }}"
    # group: "{{ wp_usergroup }}"
  notify:
    - restart apache2
  tags: [install]


- name: Wordpress config
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
  tags: [config]