---
# tasks file for wordpress


# - include: users.yml
#   tags: [config]

# - debug: msg="{{ _host_ip }}"

- name: Updating apt-Cache
  apt:
    update_cache: yes
  become: yes
  tags: [install]


- name: Install apache2
  include_role:
    name: apache2
    apply:
      tags: [install]
  vars: 
    apache2_packages: libapache2-mod-php7.2 # Ubuntu 18.04
  tags: [install]


- name: Install MySQL
  include_role:
    name: mysql
    apply:
      tags: [install]
  tags: [install]


- name: Install required packages
  package:
      name: [php7.2, php7.2-mysql, php7.2-gd, php7.2-ssh2]
      state: present
  tags: [install]


# -----------------------------------------------------------------------
# Install wordpress & configure apache
# -----------------------------------------------------------------------


- name: Download WordPress  
  get_url: 
    url: https://wordpress.org/latest.tar.gz 
    dest: /tmp/wordpress.tar.gz
    validate_certs: no


- name: Extract WordPress  
  unarchive: 
    src: /tmp/wordpress.tar.gz 
    dest: /var/www/ 
    copy: no 


- name: Copy apache vhost.conf
  template: 
    src: apache-vhost.conf.j2 
    dest: /etc/apache2/sites-available/000-default.conf 
    owner: root 
    group: root 
    mode: 0644

- name: Symlink vhost.conf from sites-available to sites-enabled
  file: 
    state: link 
    src: /etc/apache2/sites-available/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf 
    owner: root 
    group: root 
    mode: 0644


- name: Wordpress config
  template:
    src: wp-config.php.j2
    dest: "{{ wp_path }}/wp-config.php"
  tags: [install]


- name: Change ownership of installation directory
  file: 
    path: "{{ wp_path }}"
    owner: www-data 
    group: www-data  
    state: directory 
    recurse: yes 
    setype: httpd_sys_content_t


- name: Create directories
  file:
    path: "{{ wp_path }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "themes"
    - "plugins"
    - "users"
  tags: [install]


- name: Install wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: "{{ wp_cli_dir }}"
    force: true
    owner: root
    group: root
    mode: 0755
  tags: [install]


# -----------------------------------------------------------------------
# Create content  
# -----------------------------------------------------------------------


- name: Install wp-core
  command: >
    wp-cli core install
    --allow-root 
    --path='{{ wp_path }}'
    --url='{{ _host_ip }}'  
    --title='{{ wp_title }}'
    --admin_name='{{ wp_admin_name }}'
    --admin_email='{{ wp_admin_email }}'
    --admin_password='{{ wp_admin_password }}'
  tags: [install]
    

- include: empty_site.yml
  tags: [config]

- include: themes.yml
  tags: [config]

- include: plugins.yml
  tags: [config]

- include: users.yml
  tags: [config]

- include: categories.yml
  tags: [config]

- include: posts_generated.yml
  tags: [config]