---
# tasks file for wordpress


- name: Updating apt-Cache
  apt:
    update_cache: yes
  become: yes
  tags: [install]


- name: Install MariaDB
  include_role:
    name: mariadb
    apply:
      tags: [install]
  vars: 
    mariadb_databases: 
    - name: "{{ wp_mysqldb_dbname }}"
    mariadb_users:
    - {
      name: "{{ wp_mysqldb_user }}",
      host: "{{ wp_host }}",
      password: "{{ wp_mysqldb_password }}",
      privileges: "{{ wp_mysqldb_dbname }}.*:ALL,GRANT"
      }
  tags: [install]


- name: Install apache2
  include_role:
    name: apache2
    apply:
      tags: [install]
  vars: 
    apache2_packages: libapache2-mod-php7.2 # Ubuntu 18.04
    apache2_vhosts:
      - name: "{{ wp_apache_hostname }}"
        aliases: "{{ wp_apache_alias }}"
        http: true
  tags: [install]


- name: Install required packages
  package:
      name: [php7.2, php7.2-mysql, php7.2-gd, php7.2-ssh2]
      state: present
  tags: [install]


# -----------------------------------------------------------------------
# Install wordpress & configure apache
# -----------------------------------------------------------------------


- name: Check WordPress installation
  stat: 
    path: "{{ wp_path }}/wp-settings.php"
  register: wp_files_exist
  tags: [install]

- debug: msg="WordPress is not installed. Downloading ..."
  when: wp_files_exist.stat.exists == false
  tags: [install]

- debug: msg="WordPress is installed. Skipping download ..."
  when: wp_files_exist.stat.exists == true
  tags: [install]

- name: Download WordPress  
  get_url: 
    url: https://wordpress.org/latest.tar.gz 
    dest: /tmp/wordpress.tar.gz
    validate_certs: no
  when: wp_files_exist.stat.exists == false
  tags: [install]


- name: Extract WordPress  
  unarchive: 
    src: /tmp/wordpress.tar.gz 
    dest: /tmp/
    copy: no
  when: wp_files_exist.stat.exists == false
  tags: [install]


- name: Copy wordpress files
  copy: 
    remote_src: True
    src: /tmp/wordpress/
    dest: "{{ wp_path }}" 
  when: wp_files_exist.stat.exists == false
  tags: [install]


- name: Remove tmp files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/wordpress"
    - "/tmp/wordpress.tar.gz"
  when: wp_files_exist.stat.exists == false
  tags: [install]


- name: Wordpress config
  template:
    src: wp-config.php.j2
    dest: "{{ wp_path }}/wp-config.php"
  tags: [install]


- name: Change ownership of installation directory
  file: 
    path: "{{ wp_path }}"
    owner: "{{ wp_sys_user }}" 
    group: "{{ wp_sys_usergroup }}" 
    state: directory 
    recurse: yes 
    setype: httpd_sys_content_t
  tags: [install]


- name: Install wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: "{{ wp_cli_dir }}"
    force: true
    owner: root
    group: root
    mode: 0755
  tags: [install]


# -----------------------------------------------------------------------
# Create content  
# -----------------------------------------------------------------------


- name: Install wp-core
  command: >
    wp-cli core install
    --allow-root 
    --path='{{ wp_path }}'
    --url='{{ wp_host_ip }}'  
    --title='{{ wp_title }}'
    --admin_name='{{ wp_admin_name }}'
    --admin_email='{{ wp_admin_email }}'
    --admin_password='{{ wp_admin_password }}'
  tags: [install]

- name: Update tagline
  command: >
    wp-cli --allow-root --path='{{ wp_path }}' 
    option update blogdescription '{{ wp_tagline }}'
  tags: [config]

- include: empty_site.yml
  tags: [config]

- include: themes.yml
  tags: [config]

- include: plugins.yml
  tags: [config]

- include: users.yml
  tags: [config]

- include: categories.yml
  tags: [config]

- include: posts_generated.yml
  tags: [config]