---
# tasks file for wordpress_plugins

- name: Update plugins
  command: >
    wp-cli --allow-root --path='{{ wp_path }}' 
    plugin update --all
  tags: [config]


- name: Install plugins
  command: >
    wp-cli --allow-root --path='{{ wp_path }}' 
    plugin install {{ item.name }} 
    --activate
  with_items: "{{ wp_plugins }}"
  when: wp_plugins is defined
  tags: [config]