---
# tasks file for wordpress_posts_generated


- name: Create posts
  shell: >
    wp-cli --allow-root --path='{{ wp_path }}' 
    post create 
    --post_content='{{ item.content }}'
    --post_author='{{ item.author }}'
    --post_category='{{ item.category }}'
    --post_title='{{ item.title }}'
    --post_date='{{ item.date }}'
    --post_status="publish"
  with_items: "{{ wp_posts }}"
  when: wp_posts is defined
  tags: [config]