---
- name: Create category
  tags: [config]
  become: true
  become_user: "{{ wp_sys_user }}"
  ansible.builtin.command:
    cmd: >
      wp-cli --allow-root

      --path='{{ wp_path }}' --description='{{ item.description }}' term create
      category '{{ item.name }}' --skip-plugins --skip-packages --skip-themes
  register: category_result
  with_items: "{{ wp_categories }}"
  when: wp_categories is defined
  changed_when: false
  failed_when:
    - category_result.rc != 0
    - '"A term with the name provided already exists with this parent." not in category_result.stderr'
