---
- name: Remove sample content
  become: true
  become_user: '{{ wp_sys_user }}'
  ansible.builtin.command:
      cmd: >
          wp-cli  post empty --allow-root --path='{{ wp_path }}' --yes --uploads
  when: wp_remove_samples
  tags: [config]

- name: Get posts to remove
  become: true
  become_user: '{{ wp_sys_user }}'
  ansible.builtin.command:
      cmd: >
          wp-cli post list --allow-root --path='{{ wp_path }}' --post_type='{{
          item }}' --format=ids
  loop: '{{ wp_remove_posts }}'
  when: not wp_remove_samples and wp_remove_posts is defined
  register: _remove_posts
  tags: [config]

- name: Remove posts
  become: true
  become_user: '{{ wp_sys_user }}'
  ansible.builtin.command:
      cmd: >
          wp-cli post delete --allow-root --path='{{ wp_path }}' --force {{
          item.stdout }}
  loop: '{{ _remove_posts.results }}'
  when: _remove_posts is defined and item.stdout_lines | length > 0
  tags: [config]

- name: Remove uploads
  become: true
  ansible.builtin.file:
      path: '{{ wp_path }}/wp-content/uploads'
      state: absent
  when: not wp_remove_samples and wp_remove_posts is defined

- name: Ensure uploads folder exists
  become: true
  ansible.builtin.file:
      path: '{{ wp_path }}/wp-content/uploads'
      state: directory
      owner: '{{ wp_sys_user }}'
      group: '{{ wp_sys_usergroup }}'
      mode: 0644
  when: not wp_remove_samples and wp_remove_posts is defined
