---
# tasks file for wordpress_options

- name: Update Options
  become: yes
  become_user: "{{ wp_sys_user }}"
  shell: >
    wp-cli --allow-root --path='{{ wp_path }}' 
    option update {{ item.key }} '{{ item.value }}'
  with_dict: "{{ wp_options }}"
  when: item.value
  tags: [config]
