---
- name: Update plugins
  become: true
  become_user: '{{ wp_sys_user }}'
  ansible.builtin.command:
      cmd: >
          wp-cli plugin update --allow-root --path='{{ wp_path }}' --all
  tags: [config]
  when: wp_plugins_update | bool

- name: Install plugins
  become: true
  become_user: '{{ wp_sys_user }}'
  ansible.builtin.command:
      cmd: >
          wp-cli  plugin install {{ item.name }}  --user={{ wp_admin_name
          }}  --allow-root  --path='{{ wp_path }}'

          {% if item.version is defined %}
            --version='{{ item.version }}'
            --force
          {% endif %}

          {% if item.activate is defined and item.activate | bool %}
            --activate
            --activate-network
          {% endif %}
  environment:
      WP_CLI_CACHE_DIR: /tmp/.wp-cli/cache
  loop: '{{ wp_plugins }}'
  when: wp_plugins is defined
  tags: [config]
