---
- name: Install theme
  tags: [config]
  become: true
  become_user: "{{ wp_sys_user }}"
  ansible.builtin.command:
    cmd: >
      wp-cli theme install
      {{ item.name }}

      --allow-root
      --path='{{ wp_path }}'
      --skip-plugins
      --skip-packages

      {% if item.version is defined %}
        --version='{{ item.version }}'
        --force
      {% endif %}

  loop: "{{ wp_themes }}"
  when: wp_themes is defined
  changed_when: false

- name: Check install
  tags: [config]
  become: true
  become_user: "{{ wp_sys_user }}"
  ansible.builtin.command:
    cmd: >
      wp-cli theme is-installed
      {{ item.name }}

      --allow-root
      --path='{{ wp_path }}'
      --skip-plugins
      --skip-packages

  changed_when: false
  loop: "{{ wp_themes }}"
  when: wp_themes is defined

- name: Activate theme
  tags: [config]
  become: true
  become_user: "{{ wp_sys_user }}"
  ansible.builtin.command:
    cmd: >
      wp-cli theme activate
      {{ item.name }}

      --allow-root
      --path='{{ wp_path }}'
      --skip-plugins
      --skip-packages

  register: activated_theme
  changed_when: "'Success: Switched to' in activated_theme.stdout"
  loop: "{{ wp_themes }}"
  when: item.name and item.activate | default(false)
