  - src: git@github.com:ait-cs-IaaS/acr-ansible-mariadb.git
    scm: git
    version: v1.0
    name: mariadb

  - src: https://github.com/ait-cs-IaaS/acr-ansible-apache2.git
    scm: git
    version: v1.0
    name: apache2
